apiVersion: v1
kind: Service
metadata:
  name: ardana-installer-ui
spec:
  ports:
  - name: frontend
    protocol: TCP
    port: 2209
    targetPort: 2209
  - name: backend
    protocol: TCP
    port: 9085
    targetPort: 9085
  selector:
    app: ardana-installer-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ardana-installer-ui
spec:
  selector:
    matchLabels:
      app: ardana-installer-ui
  template:
    metadata:
      labels:
        app: ardana-installer-ui
    spec:
      containers:
      - name: ardana-installer-ui
        image: ardana-installer-ui-ui:latest
        ports:
        - containerPort: 2209
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ardana-service
spec:
  selector:
    matchLabels:
      app: ardana-installer-ui
  template:
    metadata:
      labels:
        app: ardana-installer-ui
    spec:
      containers:
      - name: ardana-service
        image: ardana-installer-ui-svc:latest
        ports:
        - containerPort: 9085
        imagePullPolicy: Never
